# Generated by Django 5.1 on 2025-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_google_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='google_api_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
