# Generated by Django 5.1 on 2025-07-25 22:57
from pgvector.django import VectorExtension

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0003_alter_resource_text_source'),
    ]

    operations = [
        VectorExtension(),
        migrations.RemoveField(
            model_name="resource",
            name="embeddings",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="paragraphs",
        ),
        migrations.CreateModel(
            name="ResourceChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("text", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="QA_box.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
