# Generated by Django 5.1 on 2025-07-26 01:36

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0004_remove_resource_embeddings_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourcechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='hnsw_index', opclasses=['vector_cosine_ops']),
        ),
    ]
