# Generated by Django 5.1 on 2025-07-26 01:38

from django.db import migrations

def migrate_data(apps, schema_editor):
    Resource = apps.get_model('QA_box', 'Resource')
    ResourceChunk = apps.get_model('QA_box', 'ResourceChunk')

    for resource in Resource.objects.all():
        if resource.paragraphs and resource.embeddings:
            for i, paragraph in enumerate(resource.paragraphs):
                ResourceChunk.objects.create(
                    resource=resource,
                    text=paragraph,
                    embedding=resource.embeddings[i]
                )

class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0005_resourcechunk_hnsw_index'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
