# Generated by Django 5.1 on 2025-07-26 15:19

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0006_auto_20250726_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcechunk',
            name='qaBoxes',
            field=models.ManyToManyField(related_name='chunks', to='QA_box.qabox'),
        ),
        migrations.AlterField(
            model_name='resourcechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, editable=False),
        ),
        migrations.AlterField(
            model_name='resourcechunk',
            name='text',
            field=models.TextField(editable=False),
        ),
    ]
