# Generated by Django 5.1 on 2025-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0007_resourcechunk_qaboxes_alter_resourcechunk_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcechunk',
            name='qaBoxes',
        ),
    ]
