# Generated by Django 5.1 on 2025-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0008_remove_resourcechunk_qaboxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='text_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
