# Generated by Django 5.1 on 2025-07-26 16:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0009_alter_resource_text_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, editable=False),
        ),
    ]
