# Generated by Django 5.1 on 2025-08-05 00:11

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0010_alter_resourcechunk_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcechunk',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='resourcechunk',
            name='hnsw_index',
        ),
        migrations.AddIndex(
            model_name='resourcechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='hnsw_index', opclasses=['vector_ip_ops']),
        ),
    ]
