# Generated by Django 5.1 on 2025-07-25 20:38

import ai_writing_tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0002_alter_project_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='article',
            field=models.JSONField(default=ai_writing_tools.models.get_default_article),
        ),
    ]
